// Generated by CoffeeScript 1.8.0
var calculatePonts, cleanup, handleLink, handleRoute, intervals, route_url, timeouts;

timeouts = [];

intervals = [];

handleLink = function() {
  return $('a').off('click').on('click', function(e) {
    var $el, href, path;
    $el = $(e.currentTarget);
    href = $el.attr('href');
    if (href[0] !== '/') {
      return;
    }
    e.preventDefault();
    path = url('path', href);
    route_url(path || '/');
    return false;
  });
};

cleanup = function() {
  var _results;
  while (timeouts.length) {
    clearTimeout(timeouts.pop());
  }
  _results = [];
  while (intervals.length) {
    _results.push(clearInterval(intervals.pop()));
  }
  return _results;
};

calculatePonts = function(ts) {
  var base;
  base = 1;
  return base += Math.floor((Date.now() - ts) / 1000 / 60 / 60);
};

handleRoute = function(route, $el) {
  var $form, $guesses;
  console.log(route, '123');
  switch (route) {
    case '/':
      $el.html(teacup.render(function() {
        div('.question');
        div('.guesses');
        return form('.answer-form', function() {
          input('.guess-field');
          return input({
            type: 'submit',
            value: 'submit'
          });
        });
      }));
      firebase.database().ref("active_question/public").on('value', function(data) {
        console.log(data.val());
        return $el.find('.question').html(teacup.render(function() {
          div(function() {
            return 'Welcome to the Quiz Game!\nJust answer the Current Riddle in a comment on this post and win...\nquizbot points!\nYeah! You can spend them over in the shop section';
          });
          h1(function() {
            return 'Question';
          });
          div('.text', function() {
            return "" + (data.child('question').val());
          });
          h3(function() {
            return 'Points';
          });
          return div('.points', function() {
            return "" + (calculatePonts(data.child('ts').val()));
          });
        }));
      });
      $guesses = $el.find('> .guesses');
      firebase.database().ref("guesses").limitToFirst(100).on('child_added', function(data) {
        return $guesses.append(teacup.render(function() {
          var correct;
          correct = data.child('correct').val();
          return div('.guess', function() {
            span('.name', function() {
              return data.child('answer').val();
            });
            return span('.guess', function() {
              return correct;
            });
          });
        }));
      });
      $form = $('.answer-form');
      return $form.submit(function() {
        var $guest, answer;
        $guest = $el.find('form .guess-field');
        answer = $guest.val();
        $guest.val('');
        async.waterfall([
          function(next) {
            return firebase.database().ref("active_question/public/user").set({
              'answer': answer,
              'owner': 'wakka'
            }, function(err) {
              return next(null, err == null);
            });
          }, function(correct, next) {
            return firebase.database().ref("guesses").push({
              'answer': answer,
              'correct': correct
            }, function(err) {
              return next(err);
            });
          }
        ], function(err) {
          if (err) {
            return console.log(err);
          }
        });
        return false;
      });
  }
};

route_url = function(path) {
  var $el, $link, data, new_path;
  $('#body').attr('class', '');
  path = path || url('path');
  data = path.split('/');
  history.replaceState(null, null, path);
  new_path = "/" + (data[1] || '');
  $("[data-route]").hide();
  $el = $("[data-route='" + new_path + "']");
  handleRoute(new_path, $el);
  $el.fadeIn();
  $link = $("#navigation a[href='" + new_path + "']");
  $link.addClass('active');
  return $link.siblings().removeClass('active');
};

handleLink();

$(window).load(function() {
  return route_url();
});
